### ISSUE TITLE
Taking a Backup

### ISSUE THREAD

**Issue by ICY105** [rx-modules/PlayerDB#19]
Maybe you already do this, but corruption can lead to the deletion of all scoreboard and storage data. To prevent this, I recommend copying the database to a marker every minute or so. On load, if the storage is empty, you can copy it from the marker to restore the database.

For players, I recommend their ID either be their UUID, or a hash based on their UUID so it can't change.

**Comment by RitikShah** [comment]
Hi, I saw this but forgot to respond. I'm not entirely sure what you mean by corruption, do you mean large storage files? I've done some testing with megabyte-sized storage files (using `/player` from carpet) and didn't notice any issues. Copying the entire database every minute would be considerably laggier (since the marker entity data field should be akin to saving to a jukeboxes which is a deep copy [Source](https://canary.discord.com/channels/154777837382008833/593812273164976166/831929659892826154)). Copies in pure `storage` still incur a significant amount of lag. It seems better for an exterior backup system which folks should already be doing with their worlds. Perhaps, I can add an indicator that a restore of the `storage` file should be made?

Also, boq has mentioned in mcc that storing a ton of data on a marker entity is not [a good idea](https://canary.discord.com/channels/154777837382008833/593812273164976166/831955643568619561).

I already have a system for managing player UUIDs so that player renames are captured. I provide hooks for others to use via the `api/on_name_change` function tag.

**Comment by ICY105** [comment]
On a dedicated server, it's possible for all scoreboard and storage data to be saved in a corrupted state and be deleted on restart. I'm not sure exactly what causes it (and admittedly it's pretty rare these days), but it last happened to me in 1.15- I was on a server running multiple datapacks and all storage/scoreboard data was deleted, which broke a lot of the datapacks. My best guess is it happens when the server is forcibly shutdown while trying to save a large amount of data so it gets cut off.

It's up to you if/how you want to address this issue- 99% of users probably won't notice. It may be reasonable to have it disabled by default and allow a user to enable it if they experience corruption issues.

**Comment by RitikShah** [comment]
I understand this is an unfortunate aspect of data packing in general. That being said, I don't think storing data on a `marker` entity is a good idea because it will cause serious lag on the server if it's in a loaded chunk. Otherwise, you would need to `forceload` a chunk, wait for the entity to load (since forceloading is async) and then copy the data, and this would break existing data packs using PlayerDB (potentially, perhaps I'm overthinking it).

I've been using PlayerDB on a public datapack server (which has been running since 1.9) and never have noticed scoreboard.dat corruption nor any storage corruption. We take regular backups + I even have programs that convert the `.dat` files into `.csv`s to help with looking into corruption. I think it's very difficult to be able to solve this purely via datapacks w/o any drawbacks so my recommendation would be to encourage normal backups (since worlds will probably be messed up for other reasons if those files corrupt).

I'll make sure to recommend normal backups of worlds and ensure that people backup their `data` folder (which should be anyways) to ensure folks have a safe experience! Closing for now, but feel free to open!

_Note: I do have plans for using marker entities in PlayerDB that I haven't gotten around to (like being able to access online player data instantly by having temporary marker entities)._
